# -*- coding: utf-8 -*-
"""SimpleXml.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZLBNKY4Cile4EZslasgQ0z9hMf4rZJBv
"""

import tensorflow as tf
import numpy as np # for multidimensional arrays

# Word index
word_index = {}
word_index["<PAD>"] = 0
# word_index["<START>"] = 1
word_index["<UNK>"] = 2  # unknown
# word_index["<UNUSED>"] = 3

word_index["."] = 4
word_index["validationxml"] = 5
word_index["document"] = 6
word_index["displayxml"] = 7
word_index["sheets"] = 8
word_index["sheet"] = 9
word_index["root"] = 10
word_index["node"] = 11
word_index["base"] = 12
word_index["dlitem"] = 13
word_index["member"] = 14
word_index["@X"] = 15
word_index["@Y"] = 16
word_index["@Z"] = 17

reverse_word_index = dict([(value, key) for (key, value) in word_index.items()])

test_xml_1 = "8.014999/8.014540/./validationxml/document/displayxml/sheets/sheet/document/root/node/base/base/node/base/base/dlitem/dlitem/dlitem/dlitem/dlitem/dlitem/member/@Z"
test_xml_2 = "8.014999/8.014540/./validationxml/document/displayxml/sheets/sheet/document/root/node/base/base/node/base/base/dlitem/dlitem/dlitem/dlitem/dlitem/dlitem/member/@X"
test_xml_3 = "8.014999/8.014540/./validationxml/document/displayxml/sheets/sheet/document/root/base/base/node/base/base/dlitem/dlitem/dlitem/dlitem/dlitem/dlitem/member/@Z"
test_xml_4 = "8.014999/8.014540/./validationxml/document/displayxml/sheets/sheet/document/root/base/base/node/base/base/dlitem/dlitem/dlitem/dlitem/dlitem/dlitem/member/@X"

arr_1 = test_xml_1.split('/')
